version: "3"
services:
  grafana:
    image: grafana/grafana:8.3.0
    ports:
      - 3001:3000
    volumes:
      - grafana-data:/var/lib/grafana
      # - ./provisioning:/etc/grafana/provisioning
      - ~/code/grafana-plugins:/var/lib/grafana/plugins
    environment:
      GF_LOG_LEVEL: debug 
      GF_LOG.CONSOLE_LEVEL: debug 
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-discourse-datasource 
      # GF_INSTALL_PLUGINS: marcusolsson-static-datasource,https://github.com/netsage-project/netsage-sankey-panel/releases/download/v1.0.4/netsage-sankey-panel-1.0.4.zip;netsage-sankey-panel
# Explicitly define the persistent volume for your data storage
volumes:
  grafana-data:
    external: true
